config/routes.rb
Rails.application.routes.draw do
  resources :relations
  resources :people do
    resources :relationships
  end
  get 'home/index'
  root :to => 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :relationships
  has_many :spouces, -> { joins('INNER JOIN relations ON relations.id = relationships.relation_id').where(relations: { name: 'spouce' }) },
    through: :relationships, class_name: 'Person', source: 'related_person'
  has_many :children, -> { joins('INNER JOIN relations ON relations.id = relationships.relation_id').where(relations: { name: 'child' }) },
    through: :relationships, class_name: 'Person', source: 'related_person'

  validates :name, presence: true
  validates :birth_date, presence: true

  def children_with(spouce)
    children & spouce.children # TODO: Use query instead of '&'
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :gender, :nickname, :maiden_name, :birth_date, :death_date, :contact_numbers, :whatsapp_number)
    end
end

app/views/people/_form.html.haml
= form_for @person do |f|
  - if @person.errors.any?
    #error_explanation
      %h2= "#{pluralize(@person.errors.count, "error")} prohibited this person from being saved:"
      %ul
        - @person.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :gender
    = f.select :gender, ['Male', 'Female', 'Other']
  .field
    = f.label :nickname
    = f.text_field :nickname
  .field
    = f.label :maiden_name
    = f.text_field :maiden_name
  .field
    = f.label :birth_date
    = f.date_field :birth_date
  .field
    = f.label :death_date
    = f.date_field :death_date
  .field
    = f.label :contact_numbers
    = f.text_field :contact_numbers
  .field
    = f.label :whatsapp_number
    = f.text_field :whatsapp_number
  .actions
    = f.submit 'Save'

app/views/people/edit.html.haml
%h1 Editing person

= render 'form'

= link_to 'Show', @person
\|
= link_to 'Relationships', person_relationships_path(@person)
\|
= link_to 'Back', people_path

app/views/people/index.html.haml
%h1 Listing people

%table
  %thead
    %tr
      %th Name
      %th Gender
      %th Nickname
      %th MaidenName
      %th Birthdate
      %th Deathdate
      %th Contact Number
      %th Whatsapp Number
      %th
      %th
      %th
  %tbody
    - @people.each do |person|
      %tr
        %td
          = person.name
        %td
          = person.gender
        %td
          = person.nickname
        %td
          = person.maiden_name
        %td
          = person.birth_date
        %td
          = person.death_date
        %td
          = person.contact_numbers
        %td
          = person.whatsapp_number
        %td= link_to 'Show', person
        %td= link_to 'Edit', edit_person_path(person)
        %td= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' }

%br
= link_to 'New Person', new_person_path

app/views/people/new.html.haml
%h1 New person

= render 'form'

= link_to 'Back', people_path

app/views/people/show.html.haml
%p#notice= notice
%p
  %b Name:
  = @person.name
%p
  %b Gender:
  = @person.gender
%p
  %b Nickname:
  = @person.nickname
- if @person.maiden_name
  %p
    %b MaidenName:
    = @person.maiden_name
%p
  %b Birthdate:
  = @person.birth_date
%p
  %b Deathdate:
  = @person.death_date
%p
  %b Contact Numbers:
  = @person.contact_numbers
%p
  %b Whatsapp Number:
  = @person.whatsapp_number
%b Family Tree of #{@person.name}
%hr
.family_tree_container= render_tree @person
%hr
.xxx= render_collapsible_tree @person
%hr

= link_to 'Edit', edit_person_path(@person)
\|
= link_to 'See Relationships', person_relationships_path(@person)
\|
= link_to 'New Relationship', new_person_relationship_path(@person)
\|
= link_to 'Back', people_path