config/routes.rb
Rails.application.routes.draw do
  resources :relations
  resources :people do
    resources :relationships
  end
  get 'home/index'
  root :to => 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/relation.rb
class Relation < ApplicationRecord
  has_many :relationships, dependent: :destroy

  validates :name, presence: true
end

app/controllers/relations_controller.rb
class RelationsController < ApplicationController
  before_action :set_relation, only: [:show, :edit, :update, :destroy]

  # GET /relations
  # GET /relations.json
  def index
    @relations = Relation.all
  end

  # GET /relations/1
  # GET /relations/1.json
  def show
  end

  # GET /relations/new
  def new
    @relation = Relation.new
  end

  # GET /relations/1/edit
  def edit
  end

  # POST /relations
  # POST /relations.json
  def create
    @relation = Relation.new(relation_params)

    respond_to do |format|
      if @relation.save
        format.html { redirect_to @relation, notice: 'Relation was successfully created.' }
        format.json { render :show, status: :created, location: @relation }
      else
        format.html { render :new }
        format.json { render json: @relation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /relations/1
  # PATCH/PUT /relations/1.json
  def update
    respond_to do |format|
      if @relation.update(relation_params)
        format.html { redirect_to @relation, notice: 'Relation was successfully updated.' }
        format.json { render :show, status: :ok, location: @relation }
      else
        format.html { render :edit }
        format.json { render json: @relation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /relations/1
  # DELETE /relations/1.json
  def destroy
    @relation.destroy
    respond_to do |format|
      format.html { redirect_to relations_url, notice: 'Relation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_relation
      @relation = Relation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def relation_params
      params.require(:relation).permit(:name)
    end
end

app/views/relations/_form.html.haml
= form_for @relation do |f|
  - if @relation.errors.any?
    #error_explanation
      %h2= "#{pluralize(@relation.errors.count, "error")} prohibited this relation from being saved:"
      %ul
        - @relation.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/relations/edit.html.haml
%h1 Editing relation

= render 'form'

= link_to 'Show', @relation
\|
= link_to 'Back', relations_path

app/views/relations/index.html.haml
%h1 Listing relations

%table
  %thead
    %tr
      %th Name
      %th InverseName
      %th
      %th
      %th

  %tbody
    - @relations.each do |relation|
      %tr
        %td= relation.name
        %td= link_to 'Show', relation
        %td= link_to 'Edit', edit_relation_path(relation)
        %td= link_to 'Destroy', relation, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Relation', new_relation_path

app/views/relations/new.html.haml
%h1 New relation

= render 'form'

= link_to 'Back', relations_path

app/views/relations/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @relation.name

= link_to 'Edit', edit_relation_path(@relation)
\|
= link_to 'Back', relations_path