config/routes.rb
Rails.application.routes.draw do
  resources :relations
  resources :people do
    resources :relationships
  end
  get 'home/index'
  root :to => 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :relation
  belongs_to :person
  belongs_to :related_person, class_name: 'Person'
end

app/models/relationship_type.rb
class RelationshipType < ApplicationRecord
  has_many :relationships, dependent: :destroy

  validates :name, presence: true
  validates :inverse_name, presence: true

  def name_and_backward_name
    [name, backward_name].compact.join(' --> ')
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :set_person
  before_action :set_relationship, only: [:show, :edit, :update, :destroy]

  # GET /people/1/relationships
  # GET /people/1/relationships.json
  def index
    @relationships = Relationship.where(person_id: @person.id).or(Relationship.where(related_person_id: @person.id))
  end

  # GET /people/1/relationships/1
  # GET /people/1/relationships/1.json
  def show
  end

  # GET /people/1/relationships/new
  def new
    @relationship = @person.relationships.new
  end

  # GET /people/1/relationships/1/edit
  def edit
  end

  # POST /people/1/relationships
  # POST /people/1/relationships.json
  def create
    @relationship = @person.relationships.new(relationship_params)

    respond_to do |format|
      if @relationship.save
        format.html { redirect_to [@person, @relationship], notice: 'Relationship was successfully created.' }
        format.json { render :show, status: :created, location: @relationship }
      else
        format.html { render :new }
        format.json { render json: @relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1/relationships/1
  # PATCH/PUT /people/1/relationships/1.json
  def update
    respond_to do |format|
      if @relationship.update(relationship_params)
        format.html { redirect_to [@person, @relationship], notice: 'Relationship was successfully updated.' }
        format.json { render :show, status: :ok, location: @relationship }
      else
        format.html { render :edit }
        format.json { render json: @relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1/relationships/1
  # DELETE /people/1/relationships/1.json
  def destroy
    @relationship.destroy
    respond_to do |format|
      format.html { redirect_to person_relationships_url(@person), notice: 'Relationship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:person_id])
    end

    def set_relationship
      @relationship = Relationship.where(person_id: @person.id).or(Relationship.where(related_person_id: @person.id)).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def relationship_params
      params.require(:relationship).permit(:relation_id, :related_person_id)
    end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_form.html.haml
= form_for [@person, @relationship] do |f|
  - if @relationship.errors.any?
    #error_explanation
      %h2= "#{pluralize(@relationship.errors.count, "error")} prohibited this relationship from being saved:"
      %ul
        - @relationship.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :relation
    = f.collection_select :relation_id, Relation.all, :id, :name
  .field
    = f.label :related_person
    = f.collection_select :related_person_id, Person.all, :id, :name
    Not found ?
    = link_to 'Add new', new_person_path
  .actions
    = f.submit 'Save'

app/views/relationships/edit.html.haml
%h1 Editing relationship for #{@person.name}

= render 'form'

= link_to 'Show', person_relationship_path(@person, @relationship)
\|
= link_to 'Back', person_relationships_path(@person)

app/views/relationships/index.html.haml
%h1 Listing relationships for #{@person.name}

%table
  %thead
    %tr
      %th Relation
      %th Related person
      %th
      %th
      %th

  %tbody
    - @relationships.each do |relationship|
      %tr
        %td= relationship.applicable_relation_name(@person)
        %td= link_to relationship.related_person.name, person_path(relationship.related_person)
        %td= link_to 'Show Relationship', person_relationship_path(@person, relationship)
        %td= link_to 'Edit Relationship', edit_person_relationship_path(@person, relationship)
        %td= link_to 'Remove Relationship', person_relationship_path(@person, relationship), :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Relationship', new_person_relationship_path(@person)
\|
= link_to 'Back', edit_person_path(@person)

app/views/relationships/new.html.haml
%h1 New relationship for #{@person.name}

= render 'form'

= link_to 'Back', person_path(@person)

app/views/relationships/show.html.haml
%p#notice= notice

%p
  %b Person:
  = @relationship.person.name
%p
  %b Relation:
  = @relationship.relation.name
%p
  %b Related person:
  = @relationship.related_person.name

= link_to 'Edit', edit_person_relationship_path(@person, @relationship)
\|
= link_to 'Back', person_relationships_path(@person)